export const POKEMON_RARITIES = [
  'Common',
  'Uncommon',
  'Rare',
  'Rare Holo',
  'Rare Holo EX',
  'Rare Holo GX',
  'Rare Holo V',
  'Rare Holo VMAX',
  'Rare Holo VSTAR',
  'Rare Ultra',
  'Rare Secret',
  'Illustration Rare',
  'Special Illustration Rare',
  'Hyper Rare',
  'Trainer Gallery Rare Holo',
  'Promo',
  'Double Rare',
  'ACE SPEC Rare',
  'Shiny Rare',
  'Shiny Ultra Rare',
] as const
